# -*- coding: utf-8 -*-
"""Web_scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13EJuvV_5C8wV5SeUQvy2LSIglNvLRP5N

**WEB SCRAPING USING BEAUTIFULSOUP**

Step 1: Importing necessary libraries
"""

import numpy as np
import pandas as pd
import requests
import bs4
import lxml.etree as xml

"""Step 2: creating a variable to include the url from where I am going to webscrap the data"""

URL = "https://books.toscrape.com/"
requests.get(URL)

"""Step 3: Converting the HTML page into text"""

requests.get(URL , {}).text

"""Step 4: Creating beautiful soup object from the text"""

web_page = bs4.BeautifulSoup(requests.get(URL, {}).text, "lxml")
web_page

"""Finding the title of the website"""

web_page.head.title.text

"""Body of the website"""

web_page.body

import re

# 1. Find all the "containers" that hold book information
books = web_page.find_all('article', class_='product_pod')

# 2. Create an empty list to store our data
books_list = []

for book in books:
    # Get the Title
    title = book.h3.a['title']

    # --- FIXED PRICE SECTION ---
    # Get the Price text (e.g., 'Â£51.77')
    price_text = book.find('p', class_='price_color').text

    # Use Regex to extract only the number (digits and decimal)
    # This ignores '£', 'Â', or any other encoding noise
    price_cleaned = re.findall(r"[-+]?\d*\.\d+|\d+", price_text)[0]
    price = float(price_cleaned)
    # ---------------------------

    # Get the Star Rating
    rating_classes = book.find('p', class_='star-rating')['class']
    rating = rating_classes[1]

    # Get Availability
    stock = book.find('p', class_='instock availability').text.strip()

    # Append as a dictionary to our list
    books_list.append({
        "Title": title,
        "Price": price,
        "Rating": rating,
        "Stock": stock
    })

print(f"Successfully extracted {len(books_list)} books!")

# Create the DataFrame
df = pd.DataFrame(books_list)

# Map the string ratings to numbers for better analysis
rating_map = {"One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5}
df['Rating_Num'] = df['Rating'].map(rating_map)

# Show the top 5 rows
df.head()

# Quick statistical summary of prices
print(df['Price'].describe())

# See the count of each rating
df['Rating'].value_counts().plot(kind='bar', title='Distribution of Book Ratings')

import requests
import bs4
import re

books = web_page.find_all('article', class_='product_pod')
detailed_books = []

for book in books:
    # 1. Get the 'href' attribute (NOT 'url')
    relative_url = book.h3.a['href']

    # 2. Fix the URL path
    # On this site, relative links often look like 'catalogue/book_name'
    # or '../../../book_name'. We ensure it creates a valid link.
    clean_url = relative_url.replace('../../../', '')
    if "catalogue/" in clean_url:
        full_url = "https://books.toscrape.com/" + clean_url
    else:
        full_url = "https://books.toscrape.com/catalogue/" + clean_url

    # 3. Visit the individual page
    detail_page_res = requests.get(full_url)
    detail_soup = bs4.BeautifulSoup(detail_page_res.text, "lxml")

    # 4. Extract the Product Information Table
    # Analysts love this because it's structured data
    table = detail_soup.find('table', class_='table-striped')

    if table:
        rows = table.find_all('tr')
        info_dict = {}
        for row in rows:
            header = row.th.text.strip()
            value = row.td.text.strip()
            info_dict[header] = value

        # 5. Build our data entry
        detailed_books.append({
            "Title": book.h3.a['title'],
            "UPC": info_dict.get("UPC"),
            "Price_Excl_Tax": info_dict.get("Price (excl. tax)"),
            "Tax": info_dict.get("Tax"),
            "Availability": info_dict.get("Availability")
        })

print(f"Successfully scraped details for {len(detailed_books)} books!")

import pandas as pd

# 1. Convert both lists to DataFrames
df_gallery = pd.DataFrame(books_list)
df_details = pd.DataFrame(detailed_books)

# 2. Merge them on the 'Title' column
# (In a real scenario, you'd use UPC, but Title works here!)
df_final = pd.merge(df_gallery, df_details, on="Title")

# 3. Clean up the Tax and Price columns to be purely numerical
# This makes them ready for math/statistical analysis
df_final['Tax'] = df_final['Tax'].str.extract(r'(\d+\.\d+)').astype(float)
df_final['Price_Excl_Tax'] = df_final['Price_Excl_Tax'].str.extract(r'(\d+\.\d+)').astype(float)

# 4. Save to CSV for your portfolio
df_final.to_csv("music_books_analysis.csv", index=False)

print("Master dataset created and saved as 'music_books_analysis.csv'!")
df_final.head()

import matplotlib.pyplot as plt
import seaborn as sns

# Set the visual style
sns.set_theme(style="whitegrid")

# 1. Feature Engineering: Calculate Tax Percentage
# (This is a common Data Analyst task: creating new metrics from raw data)
df_final['Tax_Rate_%'] = (df_final['Tax'] / df_final['Price_Excl_Tax']) * 100

# 2. Create a Figure with two subplots
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

# Chart 1: Price vs Tax Scatter Plot
sns.scatterplot(data=df_final, x='Price_Excl_Tax', y='Tax', hue='Rating', ax=ax1, s=100)
ax1.set_title('Relationship Between Price and Tax', fontsize=14)
ax1.set_xlabel('Price (Excl. Tax) £')
ax1.set_ylabel('Tax £')

# Chart 2: Rating Distribution
sns.countplot(data=df_final, x='Rating', order=['One', 'Two', 'Three', 'Four', 'Five'], palette='viridis', ax=ax2)
ax2.set_title('Frequency of Book Ratings', fontsize=14)
ax2.set_xlabel('Star Rating')
ax2.set_ylabel('Number of Books')

plt.tight_layout()
plt.show()

# 3. Print the Average Tax Rate to verify our math
print(f"The average tax rate across all books is: {df_final['Tax_Rate_%'].mean():.2f}%")